### PR TITLE
Add LeetCode

### PR DESCRIPTION
**Pull request by faraday**
- First download _leetcode.tar.bz2_ (502 MB) that includes these files when unpacked:
questions.jsonl                  8.1 MB
topics.jsonl                        3.47 GB
comments.jsonl                450 MB
comment_replies.jsonl    233 MB

- Group and collapse replies to their comments, comments to their topics.
- Join topics and their questions.
- Save this final table in Parquet format.

Addressing:
https://github.com/CarperAI/Code-Pile/issues/7
https://github.com/CarperAI/Code-Pile/issues/8

Statistics about the LeetCode data:

Snapshot date (until): 2022-09-26
Questions: 2421 records (7.8 MB as JSONL, 1.2 MB bzipped)
Discussion topics (pseudo-solutions): 2351568 records (3.2 GB as JSONL, 405 MB bzipped)
Comments: 525802 records(430 MB as JSONL, 46 MB bzipped)
Comment replies: 293361 records (222 MB as JSONL, 26 MB bzipped)

### CODE REVIEW

**Comment by faraday** [comment]
I'll add a commit to represent in lm_dataformat

**Comment by PhungVanDuy** [comment]
@faraday  can you add me into your repo? I will modify URL to S3 urls

**Comment by faraday** [comment]
@PhungVanDuy I just added you. Thanks

**Comment by PhungVanDuy** [comment]
Thank you so much, please update the code if have any new updates. We going to review PRs and merge soon. Thank you so much :)

**Comment by ncoop57** [comment]
@faraday can you enable me to make changes by checking this off please? https://github.blog/2016-09-07-improving-collaboration-with-forks/

**Comment by ncoop57** [comment]
So far, it looks great!

**Comment by faraday** [comment]
@ncoop57 I just added you to my fork (I read the article and thought you needed me to add you).

**Comment by ncoop57** [comment]
Thanks so much @faraday !

**Pull request merged**
